// src/renderer/components/BatchBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useQueueStore } from '../stores/queueStore'

const props = defineProps<{ selectedIds: Set<string> }>()
const emit = defineEmits<{ clear: [] }>()

const queueStore = useQueueStore()
const count = computed(() => props.selectedIds.size)

async function removeSelected() {
  for (const id of props.selectedIds) {
    await queueStore.removeItem(id)
  }
  emit('clear')
}
</script>

<template>
  <Transition name="batch">
    <div v-if="count > 0" class="batch-bar">
      <span class="count">{{ count }} selected</span>
      <div class="divider" />
      <button class="batch-btn danger" @click="removeSelected">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">
          <polyline points="3 6 5 6 21 6"/>
          <path d="M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6"/>
        </svg>
        Remove
      </button>
      <button class="batch-btn ghost" @click="emit('clear')">Cancel</button>
    </div>
  </Transition>
</template>

<style scoped>
.batch-bar {
  position: absolute;
  bottom: 36px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 18px;
  background: rgba(18,24,32,0.92);
  backdrop-filter: blur(14px);
  border: 1px solid var(--accent-glow);
  border-radius: 10px;
  box-shadow: 0 8px 32px rgba(0,0,0,0.5), 0 0 20px var(--accent-glow);
  z-index: 100;
}
.count { font-size: 12.5px; font-weight: 600; color: var(--tx-dim); }
.divider { width: 1px; height: 18px; background: var(--line-2); }
.batch-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 14px;
  border-radius: 8px;
  border: none;
  font-size: 12.5px;
  font-weight: 600;
  cursor: pointer;
  transition: filter 0.12s;
}
.batch-btn.danger { background: var(--bad); color: #fff; }
.batch-btn.danger:hover { filter: brightness(1.1); }
.batch-btn.ghost { background: var(--bg-3); color: var(--tx-dim); }
.batch-btn.ghost:hover { color: var(--tx); }

.batch-enter-active { transition: all 0.2s ease-out; }
.batch-leave-active { transition: all 0.15s ease-in; }
.batch-enter-from, .batch-leave-to { opacity: 0; transform: translateX(-50%) translateY(10px); }
</style>

// src/renderer/components/BatchBar.tsx
import { AnimatePresence, motion } from 'framer-motion'
import { PlayIcon, TrashIcon, XMarkIcon } from '@heroicons/react/24/outline'
import { batchBarVariants } from '../animations/variants'
import { useQueueStore } from '../stores/queueStore'

interface BatchBarProps {
  selectedIds: Set<string>
  onClear: () => void
}

export function BatchBar({ selectedIds, onClear }: BatchBarProps): JSX.Element {
  const count = selectedIds.size
  const removeItem = useQueueStore((s) => s.removeItem)
  const startQueue = useQueueStore((s) => s.startQueue)

  const handleRunSelected = async () => {
    await startQueue()
    onClear()
  }

  const handleRemoveSelected = async () => {
    for (const id of selectedIds) {
      await removeItem(id)
    }
    onClear()
  }

  return (
    <AnimatePresence>
      {count > 0 && (
        <motion.div
          variants={batchBarVariants}
          initial="hidden"
          animate="visible"
          exit="exit"
          className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-3 px-4 py-2.5 z-40"
          style={{
            background: 'var(--bg-1)',
            border: '1px solid var(--line-2)',
            borderRadius: 'var(--radius)',
            backdropFilter: 'blur(14px)',
            boxShadow: '0 8px 32px rgba(0,0,0,0.5)'
          }}
        >
          <span className="font-semibold" style={{ fontSize: 12.5, color: 'var(--tx-dim)' }}>
            <span className="font-mono" style={{ color: 'var(--tx)' }}>{count}</span> selected
          </span>

          <div style={{ width: 1, height: 20, background: 'var(--line-2)' }} />

          <button
            onClick={handleRunSelected}
            className="flex items-center gap-1.5 px-3 py-1.5 font-semibold transition-colors"
            style={{ fontSize: 12, color: 'var(--accent)', background: 'transparent', borderRadius: 8 }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'var(--bg-3)' }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent' }}
          >
            <PlayIcon className="w-3.5 h-3.5" />
            Run selected
          </button>

          <button
            onClick={handleRemoveSelected}
            className="flex items-center gap-1.5 px-3 py-1.5 font-semibold transition-colors"
            style={{ fontSize: 12, color: 'var(--bad)', background: 'transparent', borderRadius: 8 }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'var(--bg-3)' }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent' }}
          >
            <TrashIcon className="w-3.5 h-3.5" />
            Remove
          </button>

          <button
            onClick={onClear}
            className="flex items-center justify-center rounded-lg transition-colors"
            style={{ width: 28, height: 28, color: 'var(--tx-faint)', background: 'transparent' }}
            onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'var(--bg-3)' }}
            onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent' }}
          >
            <XMarkIcon className="w-4 h-4" />
          </button>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
