// src/renderer/components/DownloadForm.tsx
import { useState, useRef } from 'react'
import { motion } from 'framer-motion'
import { PlusIcon } from '@heroicons/react/24/outline'
import { useQueueStore } from '../stores/queueStore'
import { useToastStore } from '../stores/toastStore'
import { YOUTUBE_URL_PATTERNS } from '@shared/constants'

type Tab = 'songs' | 'playlists'

export function DownloadForm(): JSX.Element {
  const [url, setUrl] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [tab, setTab] = useState<Tab>('songs')
  const inputRef = useRef<HTMLInputElement>(null)
  const addUrl = useQueueStore((s) => s.addUrl)
  const toast = useToastStore()

  const isValidUrl = YOUTUBE_URL_PATTERNS.some((p) => p.test(url.trim()))

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    const trimmed = url.trim()
    if (!trimmed || !isValidUrl || isLoading) return

    setIsLoading(true)
    try {
      await addUrl(trimmed)
      setUrl('')
      inputRef.current?.focus()
      toast.info('Added to queue')
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to add URL')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Tabs */}
      <div className="flex gap-1" style={{ borderBottom: '1px solid var(--line)', paddingBottom: 0 }}>
        {(['songs', 'playlists'] as Tab[]).map((t) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className="px-3 py-2 font-semibold transition-colors"
            style={{
              fontSize: 11.5,
              color: tab === t ? 'var(--tx)' : 'var(--tx-faint)',
              borderBottom: tab === t ? '2px solid var(--accent)' : '2px solid transparent',
              background: 'transparent',
              textTransform: 'capitalize',
              marginBottom: -1
            }}
          >
            {t.charAt(0).toUpperCase() + t.slice(1)}
          </button>
        ))}
      </div>

      {/* Input row */}
      <form onSubmit={handleSubmit} className="flex gap-2">
        <div className="flex-1 relative">
          <input
            ref={inputRef}
            type="url"
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder={tab === 'playlists' ? 'Paste a YouTube playlist URL…' : 'Paste a YouTube URL…'}
            className="w-full px-4 py-2.5 text-sm transition-all"
            style={{
              background: 'var(--bg-2)',
              border: '1px solid var(--line-2)',
              borderRadius: 'var(--radius)',
              color: 'var(--tx)',
              fontFamily: 'Inter, system-ui, sans-serif',
              outline: 'none'
            }}
            onFocus={(e) => {
              (e.target as HTMLInputElement).style.boxShadow = '0 0 0 2px var(--accent)'
              ;(e.target as HTMLInputElement).style.borderColor = 'var(--accent)'
            }}
            onBlur={(e) => {
              (e.target as HTMLInputElement).style.boxShadow = 'none'
              ;(e.target as HTMLInputElement).style.borderColor = 'var(--line-2)'
            }}
            autoFocus
          />
          {url.length > 0 && !isValidUrl && (
            <p className="absolute -bottom-5 left-0 text-xs" style={{ color: 'var(--bad)' }}>
              Not a valid YouTube URL
            </p>
          )}
        </div>
        <motion.button
          type="submit"
          disabled={!isValidUrl || isLoading}
          whileTap={{ scale: 0.97 }}
          className="flex items-center gap-2 shrink-0 font-semibold transition-colors"
          style={{
            padding: '10px 20px',
            background: isValidUrl && !isLoading ? 'var(--accent)' : 'var(--bg-3)',
            color: isValidUrl && !isLoading ? '#fff' : 'var(--tx-faint)',
            borderRadius: 'var(--radius)',
            fontSize: 12.5,
            border: 'none',
            cursor: isValidUrl && !isLoading ? 'pointer' : 'not-allowed'
          }}
        >
          {isLoading ? (
            <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
          ) : (
            <PlusIcon className="w-4 h-4" />
          )}
          {isLoading ? 'Adding…' : 'Add to Queue'}
        </motion.button>
      </form>
    </div>
  )
}

// src/renderer/components/DownloadForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useQueueStore } from '../stores/queueStore'
import { useToastStore } from '../stores/toastStore'

const YOUTUBE_PATTERNS = [
  /^(https?:\/\/)?(www\.)?youtube\.com\/watch\?v=[\w-]+/,
  /^(https?:\/\/)?(www\.)?youtu\.be\/[\w-]+/,
  /^(https?:\/\/)?(www\.)?youtube\.com\/playlist\?list=[\w-]+/,
  /^(https?:\/\/)?(music\.)?youtube\.com\/watch\?v=[\w-]+/,
  /^(https?:\/\/)?(www\.)?soundcloud\.com\/.+/,
  /^(https?:\/\/)?.+\.bandcamp\.com\/.*/,
  /^(https?:\/\/)?bandcamp\.com\/.*/,
  /^(https?:\/\/)?(www\.)?vimeo\.com\/.+/,
]

const queueStore = useQueueStore()
const toastStore = useToastStore()

const url = ref('')
const loading = ref(false)
const error = ref('')
const tab = ref<'song' | 'playlist'>('song')

function validate(v: string) {
  return YOUTUBE_PATTERNS.some(p => p.test(v.trim()))
}

async function handleAdd() {
  error.value = ''
  const trimmed = url.value.trim()
  if (!trimmed) return
  if (!validate(trimmed)) {
    error.value = 'Please enter a valid YouTube, SoundCloud, Bandcamp or Vimeo URL'
    return
  }
  loading.value = true
  try {
    await queueStore.addUrl(trimmed)
    toastStore.add('Added to queue', 'success')
    url.value = ''
  } catch (e: any) {
    error.value = e?.message || 'Failed to add URL'
    toastStore.add(error.value, 'error')
  } finally {
    loading.value = false
  }
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') handleAdd()
}
</script>

<template>
  <div class="form-wrap">
    <div class="tabs">
      <button :class="['tab', { active: tab === 'song' }]" @click="tab = 'song'">[SONG]</button>
      <button :class="['tab', { active: tab === 'playlist' }]" @click="tab = 'playlist'">[PLAYLIST]</button>
    </div>
    <div class="input-row">
      <input
        v-model="url"
        class="url-input"
        :placeholder="tab === 'song' ? 'Paste YouTube, SoundCloud or Bandcamp URL...' : 'Paste YouTube playlist URL...'"
        :disabled="loading"
        @keydown="onKeydown"
      />
      <button class="add-btn" :disabled="loading || !url.trim()" @click="handleAdd">
        <svg v-if="!loading" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
        <svg v-else width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="spin"><path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" opacity="0.3"/><path d="M21 12a9 9 0 00-9-9"/></svg>
        {{ loading ? 'Adding...' : 'Add to Queue' }}
      </button>
    </div>
    <p v-if="error" class="error-msg">{{ error }}</p>
  </div>
</template>

<style scoped>
.form-wrap { display: flex; flex-direction: column; gap: 10px; }
.tabs { display: flex; gap: 4px; }
.tab {
  padding: 4px 12px;
  border-radius: 4px;
  border: 1px solid transparent;
  background: transparent;
  color: var(--tx-faint);
  font-size: 11px;
  font-weight: 700;
  cursor: pointer;
  transition: background 0.12s, color 0.12s, border-color 0.12s;
  font-family: 'JetBrains Mono', monospace;
  letter-spacing: 0.04em;
}
.tab:hover { background: var(--bg-3); color: var(--tx-dim); border-color: var(--line-2); }
.tab.active { background: var(--bg-3); color: var(--accent); border-color: var(--accent); }
.input-row { display: flex; gap: 8px; }
.url-input {
  flex: 1;
  height: 38px;
  padding: 0 14px;
  background: var(--bg-2);
  border: 1.5px solid var(--line-2);
  border-radius: var(--radius);
  color: var(--tx);
  font-size: 12px;
  font-family: 'JetBrains Mono', monospace;
  outline: none;
  transition: border-color 0.15s;
}
.url-input::placeholder { color: var(--tx-faint); }
.url-input:focus { border-color: var(--accent); }
.url-input:disabled { opacity: 0.5; }
.add-btn {
  height: 38px;
  padding: 0 18px;
  background: var(--accent);
  color: #fff;
  border: none;
  border-radius: var(--radius);
  font-size: 12.5px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 6px;
  white-space: nowrap;
  transition: filter 0.15s;
  flex-shrink: 0;
}
.add-btn:hover:not(:disabled) { filter: brightness(1.15); }
.add-btn:disabled { opacity: 0.5; cursor: not-allowed; }
.error-msg { font-size: 11.5px; color: var(--bad); margin: 0; }
.spin { animation: spin 0.8s linear infinite; }
@keyframes spin { to { transform: rotate(360deg); } }
</style>
