// src/renderer/components/ProgressBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { QueueStatus } from '@shared/types/queue'

const props = defineProps<{ progress: number; status: QueueStatus }>()

const color = computed(() => {
  if (props.status === 'converting' || props.status === 'tagging') return 'var(--conv)'
  if (props.status === 'completed') return 'var(--ok)'
  return 'var(--accent)'
})

const visible = computed(() =>
  ['downloading', 'converting', 'tagging', 'completed'].includes(props.status)
)
</script>

<template>
  <div v-if="visible" class="progress-track">
    <div class="progress-fill" :style="{ width: `${progress}%`, background: color }" />
  </div>
</template>

<style scoped>
.progress-track {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--line);
}
.progress-fill {
  height: 100%;
  transition: width 0.3s ease, background 0.3s ease;
}
</style>

// src/renderer/components/ProgressBar.tsx
import { motion } from 'framer-motion'
import type { QueueStatus } from '@shared/types/queue'

interface ProgressBarProps {
  progress: number
  status: QueueStatus
}

function getBarColor(status: QueueStatus): string {
  if (status === 'converting' || status === 'tagging') return 'var(--conv)'
  if (status === 'completed') return 'var(--ok)'
  if (status === 'failed') return 'var(--bad)'
  if (status === 'paused') return 'var(--warn)'
  return 'var(--accent)'
}

export function ProgressBar({ progress, status }: ProgressBarProps): JSX.Element {
  const pct = Math.min(100, Math.max(0, progress))
  const color = getBarColor(status)

  return (
    <div
      className="absolute bottom-0 left-0 right-0"
      style={{ height: 2, background: 'rgba(255,255,255,0.05)' }}
    >
      <motion.div
        className="h-full"
        style={{ background: color }}
        initial={{ width: '0%' }}
        animate={{ width: `${pct}%` }}
        transition={{ duration: 0.3, ease: 'easeOut' }}
      />
    </div>
  )
}
