// src/renderer/components/QueueList.vue
<script setup lang="ts">
import type { QueueItem } from '@shared/types/queue'
import QueueCard from './QueueItem.vue'
import { useQueueStore } from '../stores/queueStore'
import { useSettingsStore } from '../stores/settingsStore'
import { computed } from 'vue'

defineProps<{
  selectedIds: Set<string>
}>()

const emit = defineEmits<{
  toggleSelect: [id: string]
  edit: [item: QueueItem]
}>()

const queueStore = useQueueStore()
const settingsStore = useSettingsStore()
const showIndex = computed(() => settingsStore.settings.numericPrefix)
</script>

<template>
  <div class="queue-list">
    <div class="card-grid">
      <QueueCard
        v-for="(item, idx) in queueStore.items"
        :key="item.id"
        :item="item"
        :index="idx + 1"
        :selected="selectedIds.has(item.id)"
        :show-index="showIndex"
        @toggle-select="emit('toggleSelect', $event)"
        @edit="emit('edit', $event)"
      />
    </div>

    <div v-if="queueStore.items.length === 0" class="empty-state">
      <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" style="color: var(--tx-faint); margin-bottom: 12px">
        <path d="M9 18V5l12-2v13M9 18c0 1.1-1.34 2-3 2s-3-.9-3-2 1.34-2 3-2 3 .9 3 2zm12-2c0 1.1-1.34 2-3 2s-3-.9-3-2 1.34-2 3-2 3 .9 3 2z"/>
      </svg>
      <p class="empty-title">Queue is empty</p>
      <p class="empty-sub">Paste a YouTube URL above to get started</p>
    </div>
  </div>
</template>

<style scoped>
.queue-list { display: flex; flex-direction: column; min-height: 100%; }

.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
  gap: 14px;
  padding: 16px;
  align-content: start;
}

.empty-state {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
}
.empty-title { font-size: 14px; font-weight: 600; color: var(--tx-dim); margin: 0 0 4px; }
.empty-sub { font-size: 12px; color: var(--tx-faint); margin: 0; }

</style>

// src/renderer/components/QueueList.tsx
import { AnimatePresence, motion } from 'framer-motion'
import { useQueueStore } from '../stores/queueStore'
import { useIpc } from '../hooks/useIpc'
import { useToastStore } from '../stores/toastStore'
import { QueueItem } from './QueueItem'
import { useCallback } from 'react'
import type { QueueItem as QueueItemType } from '@shared/types/queue'

interface QueueListProps {
  selectedIds: Set<string>
  onToggleSelect: (id: string) => void
  onEdit: (item: QueueItemType) => void
}

export function QueueList({ selectedIds, onToggleSelect, onEdit }: QueueListProps): JSX.Element {
  const items = useQueueStore((s) => s.items)
  const updateProgress = useQueueStore((s) => s.updateProgress)
  const updateStatus = useQueueStore((s) => s.updateStatus)
  const markCompleted = useQueueStore((s) => s.markCompleted)
  const markFailed = useQueueStore((s) => s.markFailed)
  const toast = useToastStore()

  useIpc('queue:progress', useCallback(({ id, progress, status }) => {
    updateProgress(id, progress, status)
  }, [updateProgress]))

  useIpc('queue:status-changed', useCallback(({ id, status }) => {
    updateStatus(id, status)
  }, [updateStatus]))

  useIpc('queue:completed', useCallback(({ id, outputPath }) => {
    markCompleted(id, outputPath)
    toast.success('Download complete!')
  }, [markCompleted, toast]))

  useIpc('queue:error', useCallback(({ id, error }) => {
    markFailed(id, error)
    toast.error(`Download failed: ${error}`)
  }, [markFailed, toast]))

  if (items.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="flex flex-col items-center justify-center py-24"
        style={{ color: 'var(--tx-faint)' }}
      >
        <svg className="w-12 h-12 mb-4 opacity-30" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1}
            d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
        </svg>
        <p className="text-sm font-semibold" style={{ color: 'var(--tx-dim)' }}>Queue is empty</p>
        <p className="text-xs mt-1" style={{ color: 'var(--tx-faint)' }}>Add a YouTube URL above to get started</p>
      </motion.div>
    )
  }

  return (
    <div className="flex flex-col">
      <AnimatePresence mode="popLayout">
        {items.map((item, index) => (
          <QueueItem
            key={item.id}
            item={item}
            index={index}
            selected={selectedIds.has(item.id)}
            onToggleSelect={onToggleSelect}
            onEdit={onEdit}
          />
        ))}
      </AnimatePresence>
    </div>
  )
}
