// src/renderer/components/StatusBadge.tsx
import type { QueueStatus } from '@shared/types/queue'

interface StatusBadgeProps {
  status: QueueStatus
  className?: string
}

type StatusCfg = {
  label: string
  color: string
  icon: string
}

const statusConfig: Record<QueueStatus, StatusCfg> = {
  pending:     { label: 'Queued',      color: 'var(--tx-faint)', icon: '○' },
  fetching:    { label: 'Fetching',    color: 'var(--accent)',   icon: '◎' },
  downloading: { label: 'Downloading', color: 'var(--accent)',   icon: '↓' },
  converting:  { label: 'Converting',  color: 'var(--conv)',     icon: '⟳' },
  tagging:     { label: 'Tagging',     color: 'var(--conv)',     icon: '✎' },
  completed:   { label: 'Done',        color: 'var(--ok)',       icon: '✓' },
  paused:      { label: 'Paused',      color: 'var(--warn)',     icon: '⏸' },
  cancelled:   { label: 'Cancelled',   color: 'var(--tx-faint)', icon: '✕' },
  failed:      { label: 'Failed',      color: 'var(--bad)',      icon: '✕' }
}

export function StatusBadge({ status, className = '' }: StatusBadgeProps): JSX.Element {
  const cfg = statusConfig[status] ?? statusConfig.pending
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full font-mono text-[10.5px] font-bold uppercase tracking-wide shrink-0 ${className}`}
      style={{
        color: cfg.color,
        background: `color-mix(in srgb, ${cfg.color} 15%, transparent)`
      }}
    >
      <span>{cfg.icon}</span>
      {cfg.label}
    </span>
  )
}

// src/renderer/components/StatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { QueueStatus } from '@shared/types/queue'

const props = defineProps<{ status: QueueStatus }>()

const stateColor = computed(() => {
  switch (props.status) {
    case 'pending':
    case 'queued' as any:
      return 'var(--tx-faint)'
    case 'fetching':
    case 'downloading':
      return 'var(--accent)'
    case 'converting':
    case 'tagging':
      return 'var(--conv)'
    case 'paused':
      return 'var(--warn)'
    case 'completed':
      return 'var(--ok)'
    case 'failed':
    case 'cancelled':
      return 'var(--bad)'
    default:
      return 'var(--tx-faint)'
  }
})

const label = computed(() => {
  switch (props.status) {
    case 'fetching': return 'FETCHING'
    case 'downloading': return 'DOWNLOADING'
    case 'converting': return 'CONVERTING'
    case 'tagging': return 'TAGGING'
    case 'completed': return 'DONE'
    case 'failed': return 'FAILED'
    case 'cancelled': return 'CANCELLED'
    case 'paused': return 'PAUSED'
    default: return 'PENDING'
  }
})

const badgeStyle = computed(() => ({
  background: stateColor.value.startsWith('var')
    ? `color-mix(in srgb, ${stateColor.value} 15%, transparent)`
    : `${stateColor.value}26`,
  color: stateColor.value,
}))
</script>

<template>
  <span class="badge" :style="badgeStyle">{{ label }}</span>
</template>

<style scoped>
.badge {
  display: inline-flex;
  align-items: center;
  padding: 2px 7px;
  border-radius: 100px;
  font-size: 10.5px;
  font-weight: 700;
  letter-spacing: 0.03em;
  white-space: nowrap;
  line-height: 1.4;
}
</style>
