// src/renderer/pages/Dashboard.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { QueueItem } from '@shared/types/queue'
import DownloadForm from '../components/DownloadForm.vue'
import QueueList from '../components/QueueList.vue'
import BatchBar from '../components/BatchBar.vue'
import EditSheet from '../components/EditSheet.vue'
import { useQueueStore } from '../stores/queueStore'

const queueStore = useQueueStore()

const selectedIds = ref<Set<string>>(new Set())
const editItem = ref<QueueItem | null>(null)
const showForm = ref(false)

function toggleSelect(id: string) {
  const next = new Set(selectedIds.value)
  if (next.has(id)) next.delete(id)
  else next.add(id)
  selectedIds.value = next
}

function handleSave(_id: string, _artist: string, _title: string) {
  // TODO: wire up rename IPC when implemented
}
</script>

<template>
  <div class="dashboard">
    <!-- Toolbar -->
    <header class="toolbar">
      <h1 class="toolbar-title">Queue</h1>
      <span v-if="queueStore.pendingCount > 0" class="pending-count">
        {{ queueStore.pendingCount }} pending
      </span>
      <div class="spacer" />

      <div class="toolbar-actions">
        <!-- Toggle add form -->
        <button class="icon-btn" :class="{ active: showForm }" title="Add URL" @click="showForm = !showForm">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">
            <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
          </svg>
        </button>

        <!-- Clear completed -->
        <button
          v-if="queueStore.items.some(i => ['completed','cancelled','failed'].includes(i.status))"
          class="icon-btn"
          title="Clear completed"
          @click="queueStore.clearCompleted()"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">
            <polyline points="3 6 5 6 21 6"/>
            <path d="M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6"/>
          </svg>
        </button>

        <div class="sep" />

        <!-- Run queue -->
        <button v-if="!queueStore.isProcessing" class="primary-btn" @click="queueStore.startQueue()">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" fill="currentColor" stroke="none"/>
          </svg>
          Run queue
        </button>

        <template v-if="queueStore.isProcessing">
          <button v-if="!queueStore.isPaused" class="icon-btn" title="Pause" @click="queueStore.pauseQueue()">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/>
            </svg>
          </button>
          <button v-else class="icon-btn" title="Resume" @click="queueStore.resumeQueue()">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5 3 19 12 5 21 5 3"/>
            </svg>
          </button>
          <button class="icon-btn danger" title="Stop" @click="queueStore.stopQueue()">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
              <rect x="4" y="4" width="16" height="16" rx="2"/>
            </svg>
          </button>
        </template>
      </div>
    </header>

    <!-- Add form -->
    <Transition name="form-slide">
      <div v-if="showForm" class="form-panel">
        <DownloadForm />
      </div>
    </Transition>

    <!-- Queue -->
    <div class="queue-scroll">
      <QueueList
        :selected-ids="selectedIds"
        @toggle-select="toggleSelect"
        @edit="editItem = $event"
      />
    </div>

    <!-- Footer -->
    <footer class="toolbar-footer">
      <span class="footer-info">{{ queueStore.items.length }} {{ queueStore.items.length === 1 ? 'item' : 'items' }}</span>
      <span class="footer-quality">MP3 · 320 kbps</span>
    </footer>

    <!-- Batch bar -->
    <BatchBar :selected-ids="selectedIds" @clear="selectedIds = new Set()" />

    <!-- Edit sheet -->
    <EditSheet :item="editItem" @close="editItem = null" @save="handleSave" />
  </div>
</template>

<style scoped>
.dashboard { display: flex; flex-direction: column; height: 100%; position: relative; overflow: hidden; }
.toolbar {
  display: flex;
  align-items: center;
  gap: 8px;
  height: 56px;
  padding: 0 18px;
  background: var(--bg-0);
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.toolbar-title { font-size: 17px; font-weight: 800; color: var(--tx); margin: 0; }
.pending-count { font-family: 'JetBrains Mono', monospace; font-size: 11px; color: var(--tx-faint); }
.spacer { flex: 1; }
.toolbar-actions { display: flex; align-items: center; gap: 4px; }
.sep { width: 1px; height: 20px; background: var(--line-2); margin: 0 4px; }
.icon-btn {
  width: 32px; height: 32px;
  border-radius: 8px; border: none;
  background: transparent; color: var(--tx-dim);
  cursor: pointer; display: flex; align-items: center; justify-content: center;
  transition: background 0.12s, color 0.12s;
}
.icon-btn:hover { background: var(--bg-3); }
.icon-btn.active { background: var(--bg-3); color: var(--accent); }
.icon-btn.danger:hover { color: var(--bad); }
.primary-btn {
  display: flex; align-items: center; gap: 6px;
  padding: 0 18px; height: 34px;
  background: var(--accent); color: #fff;
  border: none; border-radius: var(--radius);
  font-size: 12.5px; font-weight: 600; cursor: pointer;
  transition: filter 0.15s;
}
.primary-btn:hover { filter: brightness(1.12); }
.form-panel {
  padding: 14px 18px;
  background: var(--bg-1);
  border-bottom: 1px solid var(--line);
  flex-shrink: 0;
}
.queue-scroll { flex: 1; overflow-y: auto; }
.toolbar-footer {
  display: flex; align-items: center; justify-content: space-between;
  height: 36px; padding: 0 18px;
  background: var(--bg-0); border-top: 1px solid var(--line);
  flex-shrink: 0;
}
.footer-info { font-size: 11px; color: var(--tx-faint); }
.footer-quality { font-family: 'JetBrains Mono', monospace; font-size: 11px; font-weight: 700; color: var(--accent); }

.form-slide-enter-active { transition: all 0.18s ease-out; }
.form-slide-leave-active { transition: all 0.14s ease-in; }
.form-slide-enter-from, .form-slide-leave-to { opacity: 0; transform: translateY(-6px); }
</style>

// src/renderer/pages/Dashboard.tsx
import { useState, useCallback } from 'react'
import { motion } from 'framer-motion'
import {
  PlayIcon,
  PauseIcon,
  StopIcon,
  TrashIcon,
  FunnelIcon,
  BoltIcon
} from '@heroicons/react/24/outline'
import { DownloadForm } from '../components/DownloadForm'
import { QueueList } from '../components/QueueList'
import { BatchBar } from '../components/BatchBar'
import { EditSheet } from '../components/EditSheet'
import { useQueueStore } from '../stores/queueStore'
import { useSettingsStore } from '../stores/settingsStore'
import { pageVariants } from '../animations/variants'
import type { QueueItem } from '@shared/types/queue'

export function Dashboard(): JSX.Element {
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set())
  const [editItem, setEditItem] = useState<QueueItem | null>(null)
  const [showAddForm, setShowAddForm] = useState(false)

  const items = useQueueStore((s) => s.items)
  const isProcessing = useQueueStore((s) => s.isProcessing)
  const isPaused = useQueueStore((s) => s.isPaused)
  const startQueue = useQueueStore((s) => s.startQueue)
  const pauseQueue = useQueueStore((s) => s.pauseQueue)
  const resumeQueue = useQueueStore((s) => s.resumeQueue)
  const stopQueue = useQueueStore((s) => s.stopQueue)
  const clearCompleted = useQueueStore((s) => s.clearCompleted)
  const settings = useSettingsStore((s) => s.settings)

  const hasCompletedOrFailed = items.some((i) =>
    ['completed', 'cancelled', 'failed'].includes(i.status)
  )
  const pendingCount = items.filter((i) =>
    !['completed', 'cancelled', 'failed'].includes(i.status)
  ).length
  const quality = settings?.audioQuality ?? '320'

  const handleToggleSelect = useCallback((id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }, [])

  const handleSaveEdit = useCallback((_id: string, _artist: string, _title: string) => {
    // In a full impl, update metadata via IPC
  }, [])

  return (
    <motion.div
      variants={pageVariants}
      initial="hidden"
      animate="visible"
      exit="exit"
      className="relative flex flex-col h-full overflow-hidden"
    >
      {/* Toolbar */}
      <div
        className="flex items-center px-5 shrink-0"
        style={{
          height: 56,
          background: 'var(--bg-0)',
          borderBottom: '1px solid var(--line)',
          gap: 8
        }}
      >
        <h1 style={{ fontSize: 17, fontWeight: 800, color: 'var(--tx)', flex: 'none' }}>
          Queue
        </h1>

        {pendingCount > 0 && (
          <span
            className="font-mono"
            style={{ fontSize: 11, color: 'var(--tx-faint)', marginLeft: 4 }}
          >
            {pendingCount} pending
          </span>
        )}

        <div className="flex-1" />

        {/* Right controls */}
        <div className="flex items-center gap-1">
          <IconBtn onClick={() => setShowAddForm((v) => !v)} title="Add URL">
            <FunnelIcon className="w-4 h-4" />
          </IconBtn>

          {hasCompletedOrFailed && (
            <IconBtn onClick={() => clearCompleted()} title="Clear completed">
              <TrashIcon className="w-4 h-4" />
            </IconBtn>
          )}

          <div style={{ width: 1, height: 20, background: 'var(--line-2)', margin: '0 4px' }} />

          {!isProcessing && (
            <PrimaryBtn
              onClick={() => startQueue()}
              icon={<BoltIcon className="w-4 h-4" />}
            >
              Run queue
            </PrimaryBtn>
          )}

          {isProcessing && !isPaused && (
            <IconBtn onClick={() => pauseQueue()} title="Pause">
              <PauseIcon className="w-4 h-4" />
            </IconBtn>
          )}

          {isPaused && (
            <IconBtn onClick={() => resumeQueue()} title="Resume">
              <PlayIcon className="w-4 h-4" />
            </IconBtn>
          )}

          {isProcessing && (
            <IconBtn onClick={() => stopQueue()} title="Stop" danger>
              <StopIcon className="w-4 h-4" />
            </IconBtn>
          )}
        </div>
      </div>

      {/* Add form */}
      {showAddForm && (
        <div
          className="px-5 py-4 shrink-0"
          style={{ borderBottom: '1px solid var(--line)', background: 'var(--bg-1)' }}
        >
          <DownloadForm />
        </div>
      )}

      {/* Queue table */}
      <div className="flex-1 overflow-y-auto">
        <QueueList
          selectedIds={selectedIds}
          onToggleSelect={handleToggleSelect}
          onEdit={setEditItem}
        />
      </div>

      {/* Footer */}
      <div
        className="flex items-center justify-between px-5 shrink-0"
        style={{
          height: 36,
          borderTop: '1px solid var(--line)',
          background: 'var(--bg-0)'
        }}
      >
        <span style={{ fontSize: 11, color: 'var(--tx-faint)' }}>
          {items.length} {items.length === 1 ? 'item' : 'items'} in queue
        </span>
        <span
          className="font-mono font-bold"
          style={{ fontSize: 11, color: 'var(--accent)' }}
        >
          MP3 · {quality} kbps
        </span>
      </div>

      {/* Batch bar */}
      <BatchBar selectedIds={selectedIds} onClear={() => setSelectedIds(new Set())} />

      {/* Edit sheet */}
      <EditSheet
        item={editItem}
        onClose={() => setEditItem(null)}
        onSave={handleSaveEdit}
      />
    </motion.div>
  )
}

function IconBtn({
  onClick,
  title,
  children,
  danger
}: {
  onClick: () => void
  title: string
  children: React.ReactNode
  danger?: boolean
}): JSX.Element {
  return (
    <button
      onClick={onClick}
      title={title}
      className="flex items-center justify-center rounded-lg transition-colors"
      style={{
        width: 32,
        height: 32,
        color: danger ? 'var(--bad)' : 'var(--tx-dim)',
        background: 'transparent'
      }}
      onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'var(--bg-3)' }}
      onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.background = 'transparent' }}
    >
      {children}
    </button>
  )
}

function PrimaryBtn({
  onClick,
  icon,
  children
}: {
  onClick: () => void
  icon: React.ReactNode
  children: React.ReactNode
}): JSX.Element {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-2 font-semibold transition-all"
      style={{
        padding: '10px 20px',
        background: 'var(--accent)',
        color: '#fff',
        borderRadius: 'var(--radius)',
        fontSize: 12.5,
        border: 'none',
        cursor: 'pointer'
      }}
      onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.filter = 'brightness(1.15)' }}
      onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.filter = 'none' }}
    >
      {icon}
      {children}
    </button>
  )
}
