// src/renderer/App.tsx
import { useEffect } from 'react'
import { HashRouter, Routes, Route, Navigate } from 'react-router-dom'
import { Rail } from './components/Sidebar'
import { ToastContainer } from './components/ToastContainer'
import { Dashboard } from './pages/Dashboard'
import { Settings } from './pages/Settings'
import { useQueueStore } from './stores/queueStore'
import { useSettingsStore } from './stores/settingsStore'

export default function App(): JSX.Element {
  const loadQueue = useQueueStore((s) => s.loadQueue)
  const loadSettings = useSettingsStore((s) => s.loadSettings)

  useEffect(() => {
    loadQueue()
    loadSettings()
  }, [loadQueue, loadSettings])

  return (
    <HashRouter>
      <div className="flex h-screen overflow-hidden" style={{ background: 'var(--bg-canvas)', color: 'var(--tx)' }}>
        <Rail />
        <main className="flex-1 overflow-hidden flex flex-col" style={{ background: 'var(--bg-0)' }}>
          <Routes>
            <Route path="/" element={<Navigate to="/dashboard" replace />} />
            <Route path="/dashboard" element={<Dashboard />} />
            <Route path="/settings" element={<Settings />} />
          </Routes>
        </main>
        <ToastContainer />
      </div>
    </HashRouter>
  )
}

// src/renderer/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import Rail from './components/Rail.vue'
import MiniPlayer from './components/MiniPlayer.vue'
import ToastContainer from './components/ToastContainer.vue'
import { useQueueStore } from './stores/queueStore'
import { useSettingsStore } from './stores/settingsStore'
import { useIpc } from './composables/useIpc'

const queueStore = useQueueStore()
const settingsStore = useSettingsStore()

onMounted(async () => {
  await queueStore.loadQueue()
  await settingsStore.load()
})

useIpc('queue:progress', (payload: any) => {
  queueStore.updateProgress(payload.id, payload.progress, payload.status)
})
useIpc('queue:status-changed', (payload: any) => {
  queueStore.updateStatus(payload.id, payload.status)
})
useIpc('queue:completed', (payload: any) => {
  queueStore.markCompleted(payload.id, payload.outputPath)
})
useIpc('queue:error', (payload: any) => {
  queueStore.markFailed(payload.id, payload.error)
})
</script>

<template>
  <div class="app-shell">
    <Rail />
    <div class="content-col">
      <main class="main-area">
        <RouterView />
      </main>
      <MiniPlayer />
    </div>
    <ToastContainer />
  </div>
</template>

<style scoped>
.app-shell {
  display: flex;
  height: 100vh;
  overflow: hidden;
  background: var(--bg-canvas);
  color: var(--tx);
}
.content-col {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  box-shadow: inset 4px 0 16px rgba(0,0,0,0.18);
}
.main-area {
  flex: 1;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  background: var(--bg-0);
}
</style>
